version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - devsecops-net

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - devsecops-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - devsecops-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - devsecops-net

  zap:
    image: zaproxy/zap-stable
    command: zap.sh -daemon -host 0.0.0.0 -port 8080
    ports:
      - "8081:8080"
    entrypoint: [ "tail", "-f", "/dev/null" ]  # 让容器保持运行
    networks:
      - devsecops-net

networks:
  devsecops-net:

volumes:
  jenkins_home: